//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Ogrenci_Akademisyen.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlar
    {
        public int NotID { get; set; }
        public Nullable<byte> Sinav1 { get; set; }
        public Nullable<byte> Sinav2 { get; set; }
        public Nullable<byte> Sinav3 { get; set; }
        public Nullable<byte> Quiz1 { get; set; }
        public Nullable<byte> Quiz2 { get; set; }
        public Nullable<byte> Proje { get; set; }
        public Nullable<int> Ders { get; set; }
        public Nullable<int> Ogrenci { get; set; }
    
        public virtual TblDersler TblDersler { get; set; }
        public virtual TblOgrenci TblOgrenci { get; set; }
    }
}
